import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useTranslation } from "react-i18next";
import type { TemplateVariable } from "@/hooks/use-rename";

interface DynamicFormProps {
  variables: TemplateVariable[];
  varValues: Record<string, string>;
  counterStart: number;
  onVarChange: (key: string, value: string) => void;
  onCounterChange: (value: number) => void;
}

function getVarTypeLabel(varType: string, t: (key: string) => string): string {
  const key = `template.varTypes.${varType}`;
  const translated = t(key);
  // If translation key is missing, fall back to raw type name
  return translated === key ? varType : translated;
}

function getInputLabel(label: string, t: (key: string) => string): string {
  const key = `template.inputLabels.${label}`;
  const translated = t(key);
  return translated === key ? label : translated;
}

export function DynamicForm({
  variables,
  varValues,
  counterStart,
  onVarChange,
  onCounterChange,
}: DynamicFormProps) {
  const { t } = useTranslation();

  if (variables.length === 0) {
    return null;
  }

  const hasCounter = variables.some((v) => v.varType.type === "Counter");

  return (
    <div className="space-y-3 p-4">
      {variables.map((v, index) => {
        const varType = v.varType.type;

        if (varType === "Input") {
          const rawLabel = v.label || "value";
          const label = getInputLabel(rawLabel, t);
          return (
            <div key={index} className="flex items-center gap-3">
              <Label className="w-20 shrink-0 text-sm">{label}:</Label>
              <Input
                value={varValues[rawLabel] || ""}
                onChange={(e) => onVarChange(rawLabel, e.target.value)}
                placeholder={t("template.enterValue", { label })}
                className="flex-1"
              />
            </div>
          );
        }

        if (varType === "Counter") {
          return null; // Handled separately below
        }

        // Built-in variables (Date, Time, Ext, ParentDir, OriginalName) - display only
        const displayName = getVarTypeLabel(varType, t);
        return (
          <div key={index} className="flex items-center gap-3">
            <Label className="w-20 shrink-0 text-sm text-muted-foreground">{displayName}:</Label>
            <span className="text-sm">{t("template.autoGenerated")}</span>
          </div>
        );
      })}

      {hasCounter && (
        <div className="flex items-center gap-3">
          <Label className="w-20 shrink-0 text-sm">{t("template.startAt")}</Label>
          <Input
            type="number"
            min={1}
            value={counterStart}
            onChange={(e) => {
              const val = parseInt(e.target.value, 10);
              if (!isNaN(val) && val >= 1) {
                onCounterChange(val);
              }
            }}
            className="w-24"
          />
        </div>
      )}
    </div>
  );
}