import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Calendar, Clock, FileText, FolderOpen, Hash, Type } from "lucide-react";
import { useTranslation } from "react-i18next";
import type { TemplateVariable, ItemType } from "@/hooks/use-rename";

interface DynamicFormProps {
  variables: TemplateVariable[];
  varValues: Record<string, string>;
  counterStart: number;
  onVarChange: (key: string, value: string) => void;
  onCounterChange: (value: number) => void;
  itemType?: ItemType;
}

function getVarTypeLabel(varType: string, t: (key: string) => string): string {
  const key = `template.varTypes.${varType}`;
  const translated = t(key);
  return translated === key ? varType : translated;
}

function getInputLabel(label: string, t: (key: string) => string): string {
  const key = `template.inputLabels.${label}`;
  const translated = t(key);
  return translated === key ? label : translated;
}

function getVarTypeIcon(varType: string) {
  switch (varType) {
    case "Date": return Calendar;
    case "Time": return Clock;
    case "Ext": return FileText;
    case "ParentDir": return FolderOpen;
    case "OriginalName": return FileText;
    case "Input": return Type;
    case "Counter": return Hash;
    default: return Type;
  }
}

export function DynamicForm({
  variables,
  varValues,
  counterStart,
  onVarChange,
  onCounterChange,
  itemType,
}: DynamicFormProps) {
  const { t } = useTranslation();

  if (variables.length === 0) {
    return null;
  }

  const hasCounter = variables.some((v) => v.varType.type === "Counter");
  const isFolder = itemType === "folder";

  return (
    <div className="space-y-3 p-4">
      {variables.map((v, index) => {
        const varType = v.varType.type;

        // Hide {Ext} for folders
        if (varType === "Ext" && isFolder) {
          return null;
        }

        if (varType === "Input") {
          const rawLabel = v.label || "value";
          const label = getInputLabel(rawLabel, t);
          const Icon = Type;
          return (
            <div key={index} className="flex items-center gap-3">
              <div className="flex w-20 shrink-0 items-center gap-1.5">
                <Icon className="h-3.5 w-3.5 text-muted-foreground" />
                <Label className="text-sm">{label}:</Label>
              </div>
              <Input
                value={varValues[rawLabel] || ""}
                onChange={(e) => onVarChange(rawLabel, e.target.value)}
                placeholder={t("template.enterValue", { label })}
                className="flex-1"
              />
            </div>
          );
        }

        if (varType === "Counter") {
          return null; // Handled separately below
        }

        // Built-in variables (Date, Time, Ext, ParentDir, OriginalName) - display only
        const displayName = getVarTypeLabel(varType, t);
        const Icon = getVarTypeIcon(varType);
        return (
          <div key={index} className="flex items-center gap-3">
            <div className="flex w-20 shrink-0 items-center gap-1.5">
              <Icon className="h-3.5 w-3.5 text-muted-foreground" />
              <Label className="text-sm text-muted-foreground">{displayName}:</Label>
            </div>
            <span className="text-sm text-muted-foreground/70">{t("template.autoGenerated")}</span>
          </div>
        );
      })}

      {hasCounter && (
        <div className="flex items-center gap-3">
          <div className="flex w-20 shrink-0 items-center gap-1.5">
            <Hash className="h-3.5 w-3.5 text-muted-foreground" />
            <Label className="text-sm">{t("template.startAt")}</Label>
          </div>
          <Input
            type="number"
            min={1}
            value={counterStart}
            onChange={(e) => {
              const val = parseInt(e.target.value, 10);
              if (!isNaN(val) && val >= 1) {
                onCounterChange(val);
              }
            }}
            className="w-24"
          />
        </div>
      )}
    </div>
  );
}